env = Environment(CPPPATH='#include', CCFLAGS='-g -Wall')

env.Program('chain', ['driver.c', 'src/chain.c', 'src/list.c', 'src/pair.c'])
env.Program('linear', ['driver.c', 'src/linear.c', 'src/pair.c'])
