env = Environment(CPPPATH='#include', CCFLAGS='-Wall -Wextra -g')

ds = 'src/adjlistw.c'

env.Program('dstest', ['dstest.c', 'src/iograph.c', ds, 'src/list.c'])

env.Program('iotest', ['iotest.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('copytest', ['copytest.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('transtest', ['transtest.c', 'src/iograph.c', ds, 'src/list.c'])

env.Program('dfs', ['dfsdrv.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('bfs', ['bfsdrv.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('topsort', ['topsortdrv.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('euler', ['eulerdrv.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('fcs', ['fcsdrv.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('span', ['spandrv.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('comps', ['ccdrv.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('warshall', ['warshtcdrv.c', 'src/iograph.c', 'src/adjmatnw.c', 'src/list.c'])
env.Program('bicon', ['bicondrv.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('prim', ['primdrv.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('dijkstra', ['dijkstra.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('kruskal', ['kruskal.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('floyd', ['floyd.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('dagsp', ['dagsp.c', 'src/iograph.c', ds, 'src/list.c'])
env.Program('ford', ['ford.c', 'src/iograph.c', ds, 'src/list.c'])