env = Environment(CPPPATH='#include', CCFLAGS='-Wall -g')

env.Program('iotest', ['iotest.c', 'src/iograph.c', 'src/adjlistw.c', 'src/list.c'])
env.Program('dfs', ['dfsdrv.c', 'src/iograph.c', 'src/adjlistw.c', 'src/list.c'])
env.Program('bfs', ['bfsdrv.c', 'src/iograph.c', 'src/adjlistw.c', 'src/list.c'])