env = Environment(CPPPATH='#include', CCFLAGS='-g -Wall')

env.Program('tester', 'tester.c')

env.Program('bubsort', ['driver.c', 'src/bubblesort.c', 'src/swap.c'])
env.Program('inssort', ['driver.c', 'src/insertionsort.c', 'src/swap.c'])
env.Program('selsort', ['driver.c', 'src/selectionsort.c', 'src/swap.c'])
env.Program('hsort', ['driver.c', 'src/heapsort.c', 'src/swap.c'])
env.Program('qsort', ['driver.c', 'src/quicksort.c', 'src/swap.c'])
env.Program('msort', ['driver.c', 'src/mergesort.c', 'src/swap.c'])
env.Program('shsort', ['driver.c', 'src/shellsort.c', 'src/swap.c'])
env.Program('trsort', ['driver.c', 'src/tournamentsort.c', 'src/swap.c'])